meta_product_name: "OJA"
meta_title: "OJA - Keep a track of all your job applications, easily."
meta_description: "OJA (Optimized Job Applications) is your personal job application tracker. Here to help you through the job application process and management."
meta_image: "coverimage.png" # should exist in `app/assets/images/`